### ISSUE TITLE
ZeroClipboard is not defined

### ISSUE THREAD

**Issue by zkeyword** [yiwuyu/vue-weui-ueditor#2]
E:\work\desktopApp\node_modules\vue-weui-ueditor\dist\vue-weui-ueditor.min.js:formatted:8564 Uncaught ReferenceError: ZeroClipboard is not defined

**Comment by yiwuyu** [comment]
ZeroClipboard文件是否加载成功了？

**Comment by zkeyword** [comment]
ZeroClipboard文件要额外引用才正常  你应该给整合到组件内

**Comment by yiwuyu** [comment]
这个版本已经把额外的附件都推送到了unpkg上了
![image](https://user-images.githubusercontent.com/25633994/28675083-5aeca886-7319-11e7-9158-0a52371a6a40.png)
你没有用下面的方式导入到项目中对吧？
```
npm install vue-weui-ueditor --S
```
